name: Backend CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          npm install

      # Step 4: Run tests
      - name: Run tests
        run: |
          npm test

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      # Step 1: কোড চেকআউট করা
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: ডিপ্লয়মেন্ট কমান্ড চালানো
      - name: Deploy Backend
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          working-directory: .
